//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomM.WebServiceTest.AssetService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/RoomM.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoomM.WebServiceTest.AssetService.RoomAssetHistory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoomM.WebServiceTest.AssetService.HistoryType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoomM.WebServiceTest.AssetService.Room))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoomM.WebServiceTest.AssetService.RoomAsset))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoomM.WebServiceTest.AssetService.RoomCalendar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoomM.WebServiceTest.AssetService.RoomCalendarStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoomM.WebServiceTest.AssetService.Staff))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoomM.WebServiceTest.AssetService.StaffType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoomM.WebServiceTest.AssetService.RoomType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoomM.WebServiceTest.AssetService.Asset))]
    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomAssetHistory", Namespace="http://schemas.datacontract.org/2004/07/RoomM.Models")]
    [System.SerializableAttribute()]
    public partial class RoomAssetHistory : RoomM.WebServiceTest.AssetService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.Asset AssetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AssetHistoryTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AssetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.HistoryType HistoryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.Room RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Room2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RoomIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.Asset Asset {
            get {
                return this.AssetField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetField, value) != true)) {
                    this.AssetField = value;
                    this.RaisePropertyChanged("Asset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AssetHistoryTypeId {
            get {
                return this.AssetHistoryTypeIdField;
            }
            set {
                if ((this.AssetHistoryTypeIdField.Equals(value) != true)) {
                    this.AssetHistoryTypeIdField = value;
                    this.RaisePropertyChanged("AssetHistoryTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AssetId {
            get {
                return this.AssetIdField;
            }
            set {
                if ((this.AssetIdField.Equals(value) != true)) {
                    this.AssetIdField = value;
                    this.RaisePropertyChanged("AssetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.HistoryType HistoryType {
            get {
                return this.HistoryTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.HistoryTypeField, value) != true)) {
                    this.HistoryTypeField = value;
                    this.RaisePropertyChanged("HistoryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.Room Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Room2 {
            get {
                return this.Room2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Room2Field, value) != true)) {
                    this.Room2Field = value;
                    this.RaisePropertyChanged("Room2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RoomId {
            get {
                return this.RoomIdField;
            }
            set {
                if ((this.RoomIdField.Equals(value) != true)) {
                    this.RoomIdField = value;
                    this.RaisePropertyChanged("RoomId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryType", Namespace="http://schemas.datacontract.org/2004/07/RoomM.Models")]
    [System.SerializableAttribute()]
    public partial class HistoryType : RoomM.WebServiceTest.AssetService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.RoomAssetHistory[] AssetHistoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.RoomAssetHistory[] AssetHistories {
            get {
                return this.AssetHistoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetHistoriesField, value) != true)) {
                    this.AssetHistoriesField = value;
                    this.RaisePropertyChanged("AssetHistories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Room", Namespace="http://schemas.datacontract.org/2004/07/RoomM.Models")]
    [System.SerializableAttribute()]
    public partial class Room : RoomM.WebServiceTest.AssetService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.RoomAssetHistory[] AssetHistoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUsingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.RoomAsset[] RoomAssetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.RoomCalendar[] RoomCalendarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.RoomType RoomTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RoomTypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.RoomAssetHistory[] AssetHistories {
            get {
                return this.AssetHistoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetHistoriesField, value) != true)) {
                    this.AssetHistoriesField = value;
                    this.RaisePropertyChanged("AssetHistories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreate {
            get {
                return this.DateCreateField;
            }
            set {
                if ((this.DateCreateField.Equals(value) != true)) {
                    this.DateCreateField = value;
                    this.RaisePropertyChanged("DateCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUsing {
            get {
                return this.IsUsingField;
            }
            set {
                if ((this.IsUsingField.Equals(value) != true)) {
                    this.IsUsingField = value;
                    this.RaisePropertyChanged("IsUsing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.RoomAsset[] RoomAssets {
            get {
                return this.RoomAssetsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomAssetsField, value) != true)) {
                    this.RoomAssetsField = value;
                    this.RaisePropertyChanged("RoomAssets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.RoomCalendar[] RoomCalendars {
            get {
                return this.RoomCalendarsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomCalendarsField, value) != true)) {
                    this.RoomCalendarsField = value;
                    this.RaisePropertyChanged("RoomCalendars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.RoomType RoomType {
            get {
                return this.RoomTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeField, value) != true)) {
                    this.RoomTypeField = value;
                    this.RaisePropertyChanged("RoomType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RoomTypeId {
            get {
                return this.RoomTypeIdField;
            }
            set {
                if ((this.RoomTypeIdField.Equals(value) != true)) {
                    this.RoomTypeIdField = value;
                    this.RaisePropertyChanged("RoomTypeId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomAsset", Namespace="http://schemas.datacontract.org/2004/07/RoomM.Models")]
    [System.SerializableAttribute()]
    public partial class RoomAsset : RoomM.WebServiceTest.AssetService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.Asset AssetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AssetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.Room RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RoomIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.Asset Asset {
            get {
                return this.AssetField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetField, value) != true)) {
                    this.AssetField = value;
                    this.RaisePropertyChanged("Asset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AssetId {
            get {
                return this.AssetIdField;
            }
            set {
                if ((this.AssetIdField.Equals(value) != true)) {
                    this.AssetIdField = value;
                    this.RaisePropertyChanged("AssetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.Room Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RoomId {
            get {
                return this.RoomIdField;
            }
            set {
                if ((this.RoomIdField.Equals(value) != true)) {
                    this.RoomIdField = value;
                    this.RaisePropertyChanged("RoomId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomCalendar", Namespace="http://schemas.datacontract.org/2004/07/RoomM.Models")]
    [System.SerializableAttribute()]
    public partial class RoomCalendar : RoomM.WebServiceTest.AssetService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWatchedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.Room RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.RoomCalendarStatus RoomCalendarStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RoomCalendarStatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RoomIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.Staff StaffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long StaffIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWatched {
            get {
                return this.IsWatchedField;
            }
            set {
                if ((this.IsWatchedField.Equals(value) != true)) {
                    this.IsWatchedField = value;
                    this.RaisePropertyChanged("IsWatched");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.Room Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.RoomCalendarStatus RoomCalendarStatus {
            get {
                return this.RoomCalendarStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomCalendarStatusField, value) != true)) {
                    this.RoomCalendarStatusField = value;
                    this.RaisePropertyChanged("RoomCalendarStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RoomCalendarStatusId {
            get {
                return this.RoomCalendarStatusIdField;
            }
            set {
                if ((this.RoomCalendarStatusIdField.Equals(value) != true)) {
                    this.RoomCalendarStatusIdField = value;
                    this.RaisePropertyChanged("RoomCalendarStatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RoomId {
            get {
                return this.RoomIdField;
            }
            set {
                if ((this.RoomIdField.Equals(value) != true)) {
                    this.RoomIdField = value;
                    this.RaisePropertyChanged("RoomId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.Staff Staff {
            get {
                return this.StaffField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffField, value) != true)) {
                    this.StaffField = value;
                    this.RaisePropertyChanged("Staff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long StaffId {
            get {
                return this.StaffIdField;
            }
            set {
                if ((this.StaffIdField.Equals(value) != true)) {
                    this.StaffIdField = value;
                    this.RaisePropertyChanged("StaffId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomCalendarStatus", Namespace="http://schemas.datacontract.org/2004/07/RoomM.Models")]
    [System.SerializableAttribute()]
    public partial class RoomCalendarStatus : RoomM.WebServiceTest.AssetService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.RoomCalendar[] RoomCalendarsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.RoomCalendar[] RoomCalendars {
            get {
                return this.RoomCalendarsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomCalendarsField, value) != true)) {
                    this.RoomCalendarsField = value;
                    this.RaisePropertyChanged("RoomCalendars");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://schemas.datacontract.org/2004/07/RoomM.Models")]
    [System.SerializableAttribute()]
    public partial class Staff : RoomM.WebServiceTest.AssetService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWorkingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordStoredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.RoomCalendar[] RoomCalendarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.StaffType StaffTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long StaffTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWorking {
            get {
                return this.IsWorkingField;
            }
            set {
                if ((this.IsWorkingField.Equals(value) != true)) {
                    this.IsWorkingField = value;
                    this.RaisePropertyChanged("IsWorking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastLogin {
            get {
                return this.LastLoginField;
            }
            set {
                if ((this.LastLoginField.Equals(value) != true)) {
                    this.LastLoginField = value;
                    this.RaisePropertyChanged("LastLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordStored {
            get {
                return this.PasswordStoredField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordStoredField, value) != true)) {
                    this.PasswordStoredField = value;
                    this.RaisePropertyChanged("PasswordStored");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.RoomCalendar[] RoomCalendars {
            get {
                return this.RoomCalendarsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomCalendarsField, value) != true)) {
                    this.RoomCalendarsField = value;
                    this.RaisePropertyChanged("RoomCalendars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.StaffType StaffType {
            get {
                return this.StaffTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffTypeField, value) != true)) {
                    this.StaffTypeField = value;
                    this.RaisePropertyChanged("StaffType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long StaffTypeId {
            get {
                return this.StaffTypeIdField;
            }
            set {
                if ((this.StaffTypeIdField.Equals(value) != true)) {
                    this.StaffTypeIdField = value;
                    this.RaisePropertyChanged("StaffTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StaffType", Namespace="http://schemas.datacontract.org/2004/07/RoomM.Models")]
    [System.SerializableAttribute()]
    public partial class StaffType : RoomM.WebServiceTest.AssetService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.Staff[] StaffsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.Staff[] Staffs {
            get {
                return this.StaffsField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffsField, value) != true)) {
                    this.StaffsField = value;
                    this.RaisePropertyChanged("Staffs");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomType", Namespace="http://schemas.datacontract.org/2004/07/RoomM.Models")]
    [System.SerializableAttribute()]
    public partial class RoomType : RoomM.WebServiceTest.AssetService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.Room[] RoomsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.Room[] Rooms {
            get {
                return this.RoomsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomsField, value) != true)) {
                    this.RoomsField = value;
                    this.RaisePropertyChanged("Rooms");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Asset", Namespace="http://schemas.datacontract.org/2004/07/RoomM.Models")]
    [System.SerializableAttribute()]
    public partial class Asset : RoomM.WebServiceTest.AssetService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.RoomAssetHistory[] AssetHistoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUsingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoomM.WebServiceTest.AssetService.RoomAsset[] RoomAssetsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.RoomAssetHistory[] AssetHistories {
            get {
                return this.AssetHistoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetHistoriesField, value) != true)) {
                    this.AssetHistoriesField = value;
                    this.RaisePropertyChanged("AssetHistories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUsing {
            get {
                return this.IsUsingField;
            }
            set {
                if ((this.IsUsingField.Equals(value) != true)) {
                    this.IsUsingField = value;
                    this.RaisePropertyChanged("IsUsing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoomM.WebServiceTest.AssetService.RoomAsset[] RoomAssets {
            get {
                return this.RoomAssetsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomAssetsField, value) != true)) {
                    this.RoomAssetsField = value;
                    this.RaisePropertyChanged("RoomAssets");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AssetService.IAssetService")]
    public interface IAssetService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/GetSingle", ReplyAction="http://tempuri.org/IAssetService/GetSingleResponse")]
        RoomM.WebServiceTest.AssetService.Asset GetSingle(int deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/GetSingle", ReplyAction="http://tempuri.org/IAssetService/GetSingleResponse")]
        System.Threading.Tasks.Task<RoomM.WebServiceTest.AssetService.Asset> GetSingleAsync(int deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/GetNameList", ReplyAction="http://tempuri.org/IAssetService/GetNameListResponse")]
        string[] GetNameList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/GetNameList", ReplyAction="http://tempuri.org/IAssetService/GetNameListResponse")]
        System.Threading.Tasks.Task<string[]> GetNameListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/isUniqueName", ReplyAction="http://tempuri.org/IAssetService/isUniqueNameResponse")]
        bool isUniqueName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/isUniqueName", ReplyAction="http://tempuri.org/IAssetService/isUniqueNameResponse")]
        System.Threading.Tasks.Task<bool> isUniqueNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAssetServiceChannel : RoomM.WebServiceTest.AssetService.IAssetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AssetServiceClient : System.ServiceModel.ClientBase<RoomM.WebServiceTest.AssetService.IAssetService>, RoomM.WebServiceTest.AssetService.IAssetService {
        
        public AssetServiceClient() {
        }
        
        public AssetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AssetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RoomM.WebServiceTest.AssetService.Asset GetSingle(int deviceId) {
            return base.Channel.GetSingle(deviceId);
        }
        
        public System.Threading.Tasks.Task<RoomM.WebServiceTest.AssetService.Asset> GetSingleAsync(int deviceId) {
            return base.Channel.GetSingleAsync(deviceId);
        }
        
        public string[] GetNameList() {
            return base.Channel.GetNameList();
        }
        
        public System.Threading.Tasks.Task<string[]> GetNameListAsync() {
            return base.Channel.GetNameListAsync();
        }
        
        public bool isUniqueName(string name) {
            return base.Channel.isUniqueName(name);
        }
        
        public System.Threading.Tasks.Task<bool> isUniqueNameAsync(string name) {
            return base.Channel.isUniqueNameAsync(name);
        }
    }
}
