//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomM.WebServiceTest.RoomTypeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomTypeService.IRoomTypeService")]
    public interface IRoomTypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTypeService/GetSingle", ReplyAction="http://tempuri.org/IRoomTypeService/GetSingleResponse")]
        RoomM.Models.Rooms.RoomType GetSingle(int roomTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTypeService/GetSingle", ReplyAction="http://tempuri.org/IRoomTypeService/GetSingleResponse")]
        System.Threading.Tasks.Task<RoomM.Models.Rooms.RoomType> GetSingleAsync(int roomTypeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomTypeServiceChannel : RoomM.WebServiceTest.RoomTypeService.IRoomTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomTypeServiceClient : System.ServiceModel.ClientBase<RoomM.WebServiceTest.RoomTypeService.IRoomTypeService>, RoomM.WebServiceTest.RoomTypeService.IRoomTypeService {
        
        public RoomTypeServiceClient() {
        }
        
        public RoomTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RoomM.Models.Rooms.RoomType GetSingle(int roomTypeId) {
            return base.Channel.GetSingle(roomTypeId);
        }
        
        public System.Threading.Tasks.Task<RoomM.Models.Rooms.RoomType> GetSingleAsync(int roomTypeId) {
            return base.Channel.GetSingleAsync(roomTypeId);
        }
    }
}
