//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomM.WebServiceTest.RoomService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomService.IRoomService")]
    public interface IRoomService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetSingle", ReplyAction="http://tempuri.org/IRoomService/GetSingleResponse")]
        RoomM.Models.Rooms.Room GetSingle(long roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetSingle", ReplyAction="http://tempuri.org/IRoomService/GetSingleResponse")]
        System.Threading.Tasks.Task<RoomM.Models.Rooms.Room> GetSingleAsync(long roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetByRoomTypeId", ReplyAction="http://tempuri.org/IRoomService/GetByRoomTypeIdResponse")]
        RoomM.Models.Rooms.Room[] GetByRoomTypeId(long roomTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetByRoomTypeId", ReplyAction="http://tempuri.org/IRoomService/GetByRoomTypeIdResponse")]
        System.Threading.Tasks.Task<RoomM.Models.Rooms.Room[]> GetByRoomTypeIdAsync(long roomTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetRoomListLimitByRegister", ReplyAction="http://tempuri.org/IRoomService/GetRoomListLimitByRegisterResponse")]
        RoomM.Models.Rooms.Room[] GetRoomListLimitByRegister(int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetRoomListLimitByRegister", ReplyAction="http://tempuri.org/IRoomService/GetRoomListLimitByRegisterResponse")]
        System.Threading.Tasks.Task<RoomM.Models.Rooms.Room[]> GetRoomListLimitByRegisterAsync(int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetRoomLimitByRegister", ReplyAction="http://tempuri.org/IRoomService/GetRoomLimitByRegisterResponse")]
        System.Collections.DictionaryEntry[] GetRoomLimitByRegister(int limit, System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetRoomLimitByRegister", ReplyAction="http://tempuri.org/IRoomService/GetRoomLimitByRegisterResponse")]
        System.Threading.Tasks.Task<System.Collections.DictionaryEntry[]> GetRoomLimitByRegisterAsync(int limit, System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/isUniqueName", ReplyAction="http://tempuri.org/IRoomService/isUniqueNameResponse")]
        bool isUniqueName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/isUniqueName", ReplyAction="http://tempuri.org/IRoomService/isUniqueNameResponse")]
        System.Threading.Tasks.Task<bool> isUniqueNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomServiceChannel : RoomM.WebServiceTest.RoomService.IRoomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomServiceClient : System.ServiceModel.ClientBase<RoomM.WebServiceTest.RoomService.IRoomService>, RoomM.WebServiceTest.RoomService.IRoomService {
        
        public RoomServiceClient() {
        }
        
        public RoomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RoomM.Models.Rooms.Room GetSingle(long roomId) {
            return base.Channel.GetSingle(roomId);
        }
        
        public System.Threading.Tasks.Task<RoomM.Models.Rooms.Room> GetSingleAsync(long roomId) {
            return base.Channel.GetSingleAsync(roomId);
        }
        
        public RoomM.Models.Rooms.Room[] GetByRoomTypeId(long roomTypeId) {
            return base.Channel.GetByRoomTypeId(roomTypeId);
        }
        
        public System.Threading.Tasks.Task<RoomM.Models.Rooms.Room[]> GetByRoomTypeIdAsync(long roomTypeId) {
            return base.Channel.GetByRoomTypeIdAsync(roomTypeId);
        }
        
        public RoomM.Models.Rooms.Room[] GetRoomListLimitByRegister(int limit) {
            return base.Channel.GetRoomListLimitByRegister(limit);
        }
        
        public System.Threading.Tasks.Task<RoomM.Models.Rooms.Room[]> GetRoomListLimitByRegisterAsync(int limit) {
            return base.Channel.GetRoomListLimitByRegisterAsync(limit);
        }
        
        public System.Collections.DictionaryEntry[] GetRoomLimitByRegister(int limit, System.DateTime from, System.DateTime to) {
            return base.Channel.GetRoomLimitByRegister(limit, from, to);
        }
        
        public System.Threading.Tasks.Task<System.Collections.DictionaryEntry[]> GetRoomLimitByRegisterAsync(int limit, System.DateTime from, System.DateTime to) {
            return base.Channel.GetRoomLimitByRegisterAsync(limit, from, to);
        }
        
        public bool isUniqueName(string name) {
            return base.Channel.isUniqueName(name);
        }
        
        public System.Threading.Tasks.Task<bool> isUniqueNameAsync(string name) {
            return base.Channel.isUniqueNameAsync(name);
        }
    }
}
