//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomM.DeskApp.RoomCalendarStatusService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomCalendarStatusService.IRoomCalendarStatusService")]
    public interface IRoomCalendarStatusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_RoomCalendarStatus/GetSingle", ReplyAction="http://tempuri.org/IServiceOf_RoomCalendarStatus/GetSingleResponse")]
        RoomM.Models.RoomCalendarStatus GetSingle(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_RoomCalendarStatus/GetSingle", ReplyAction="http://tempuri.org/IServiceOf_RoomCalendarStatus/GetSingleResponse")]
        System.Threading.Tasks.Task<RoomM.Models.RoomCalendarStatus> GetSingleAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_RoomCalendarStatus/GetAll", ReplyAction="http://tempuri.org/IServiceOf_RoomCalendarStatus/GetAllResponse")]
        System.Collections.Generic.List<RoomM.Models.RoomCalendarStatus> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_RoomCalendarStatus/GetAll", ReplyAction="http://tempuri.org/IServiceOf_RoomCalendarStatus/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<RoomM.Models.RoomCalendarStatus>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_RoomCalendarStatus/Add", ReplyAction="http://tempuri.org/IServiceOf_RoomCalendarStatus/AddResponse")]
        void Add(RoomM.Models.RoomCalendarStatus entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_RoomCalendarStatus/Add", ReplyAction="http://tempuri.org/IServiceOf_RoomCalendarStatus/AddResponse")]
        System.Threading.Tasks.Task AddAsync(RoomM.Models.RoomCalendarStatus entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_RoomCalendarStatus/DeleteByT", ReplyAction="http://tempuri.org/IServiceOf_RoomCalendarStatus/DeleteByTResponse")]
        void DeleteByT(RoomM.Models.RoomCalendarStatus entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_RoomCalendarStatus/DeleteByT", ReplyAction="http://tempuri.org/IServiceOf_RoomCalendarStatus/DeleteByTResponse")]
        System.Threading.Tasks.Task DeleteByTAsync(RoomM.Models.RoomCalendarStatus entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_RoomCalendarStatus/DeleteByObject", ReplyAction="http://tempuri.org/IServiceOf_RoomCalendarStatus/DeleteByObjectResponse")]
        void DeleteByObject(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_RoomCalendarStatus/DeleteByObject", ReplyAction="http://tempuri.org/IServiceOf_RoomCalendarStatus/DeleteByObjectResponse")]
        System.Threading.Tasks.Task DeleteByObjectAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_RoomCalendarStatus/Edit", ReplyAction="http://tempuri.org/IServiceOf_RoomCalendarStatus/EditResponse")]
        void Edit(RoomM.Models.RoomCalendarStatus entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_RoomCalendarStatus/Edit", ReplyAction="http://tempuri.org/IServiceOf_RoomCalendarStatus/EditResponse")]
        System.Threading.Tasks.Task EditAsync(RoomM.Models.RoomCalendarStatus entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomCalendarStatusService/GetNameList", ReplyAction="http://tempuri.org/IRoomCalendarStatusService/GetNameListResponse")]
        System.Collections.Generic.List<string> GetNameList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomCalendarStatusService/GetNameList", ReplyAction="http://tempuri.org/IRoomCalendarStatusService/GetNameListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetNameListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomCalendarStatusServiceChannel : RoomM.DeskApp.RoomCalendarStatusService.IRoomCalendarStatusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomCalendarStatusServiceClient : System.ServiceModel.ClientBase<RoomM.DeskApp.RoomCalendarStatusService.IRoomCalendarStatusService>, RoomM.DeskApp.RoomCalendarStatusService.IRoomCalendarStatusService {
        
        public RoomCalendarStatusServiceClient() {
        }
        
        public RoomCalendarStatusServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomCalendarStatusServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomCalendarStatusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomCalendarStatusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RoomM.Models.RoomCalendarStatus GetSingle(long id) {
            return base.Channel.GetSingle(id);
        }
        
        public System.Threading.Tasks.Task<RoomM.Models.RoomCalendarStatus> GetSingleAsync(long id) {
            return base.Channel.GetSingleAsync(id);
        }
        
        public System.Collections.Generic.List<RoomM.Models.RoomCalendarStatus> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<RoomM.Models.RoomCalendarStatus>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void Add(RoomM.Models.RoomCalendarStatus entity) {
            base.Channel.Add(entity);
        }
        
        public System.Threading.Tasks.Task AddAsync(RoomM.Models.RoomCalendarStatus entity) {
            return base.Channel.AddAsync(entity);
        }
        
        public void DeleteByT(RoomM.Models.RoomCalendarStatus entity) {
            base.Channel.DeleteByT(entity);
        }
        
        public System.Threading.Tasks.Task DeleteByTAsync(RoomM.Models.RoomCalendarStatus entity) {
            return base.Channel.DeleteByTAsync(entity);
        }
        
        public void DeleteByObject(long id) {
            base.Channel.DeleteByObject(id);
        }
        
        public System.Threading.Tasks.Task DeleteByObjectAsync(long id) {
            return base.Channel.DeleteByObjectAsync(id);
        }
        
        public void Edit(RoomM.Models.RoomCalendarStatus entity) {
            base.Channel.Edit(entity);
        }
        
        public System.Threading.Tasks.Task EditAsync(RoomM.Models.RoomCalendarStatus entity) {
            return base.Channel.EditAsync(entity);
        }
        
        public System.Collections.Generic.List<string> GetNameList() {
            return base.Channel.GetNameList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetNameListAsync() {
            return base.Channel.GetNameListAsync();
        }
    }
}
