//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomM.WebServiceTest.StaffTypeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StaffTypeService.IStaffTypeService")]
    public interface IStaffTypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffTypeService/GetSingle", ReplyAction="http://tempuri.org/IStaffTypeService/GetSingleResponse")]
        RoomM.Models.Staffs.StaffType GetSingle(int staffTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffTypeService/GetSingle", ReplyAction="http://tempuri.org/IStaffTypeService/GetSingleResponse")]
        System.Threading.Tasks.Task<RoomM.Models.Staffs.StaffType> GetSingleAsync(int staffTypeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStaffTypeServiceChannel : RoomM.WebServiceTest.StaffTypeService.IStaffTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StaffTypeServiceClient : System.ServiceModel.ClientBase<RoomM.WebServiceTest.StaffTypeService.IStaffTypeService>, RoomM.WebServiceTest.StaffTypeService.IStaffTypeService {
        
        public StaffTypeServiceClient() {
        }
        
        public StaffTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StaffTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RoomM.Models.Staffs.StaffType GetSingle(int staffTypeId) {
            return base.Channel.GetSingle(staffTypeId);
        }
        
        public System.Threading.Tasks.Task<RoomM.Models.Staffs.StaffType> GetSingleAsync(int staffTypeId) {
            return base.Channel.GetSingleAsync(staffTypeId);
        }
    }
}
